const fs=require('fs');
const c=fs.readFileSync('index.html','utf8');
console.log('=== ENCODING CHECK (real) ===');
const tests=['Conexão','Não','Manutenção','ação','Créditos','Bônus'];
tests.forEach(w=>console.log(w+':',c.includes(w)?'OK':'MISSING'));
console.log('=== EMOJIS ===');
['🎯','💰','🔑','⚙️','🔄','🎟️'].forEach(e=>console.log(e+':',c.includes(e)?'OK':'MISSING'));
console.log('=== 116 IDs ===');
const net=fs.readFileSync('network.js','utf8');
const gl=fs.readFileSync('game-logic.js','utf8');
const netIds=[...net.matchAll(/document\.getElementById\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const glIds=[...gl.matchAll(/document\.getElementById\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const allIds=new Set([...netIds,...glIds]);
const htmlIds=new Set([...c.matchAll(/id=["']([^"']+)["']/g)].map(m=>m[1]));
const dynamic=new Set(['editNome','editEmail','editSenha','editPix','editStatus','kenoRankingOverlay','soundHint']);
const missing=[];
allIds.forEach(id=>{if(!htmlIds.has(id)&&!dynamic.has(id))missing.push(id)});
if(missing.length===0)console.log('ALL '+allIds.size+' IDs PRESENT');
else console.log('MISSING ('+missing.length+'):',missing.join(', '));
console.log('Size:',c.length,'bytes');
